# Generated by Django 5.2 on 2025-06-03 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Nickname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nicknames', to='core.event')),
            ],
            options={
                'ordering': ['-total_score', 'name'],
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ActivityRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nickname')),
            ],
            options={
                'ordering': ['activity_id', 'rank'],
                'unique_together': {('event', 'nickname', 'activity_id')},
            },
        ),
        migrations.CreateModel(
            name='TennisMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tennis_matches_as_player1', to='core.nickname')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tennis_matches_as_player2', to='core.nickname')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tennis_wins', to='core.nickname')),
            ],
            options={
                'unique_together': {('event', 'player1', 'player2')},
            },
        ),
    ]
