# Generated by Django 5.2 on 2025-10-13 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_seconds', models.FloatField()),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nickname')),
            ],
            options={
                'ordering': ['time_seconds'],
                'unique_together': {('event', 'nickname')},
            },
        ),
    ]
