# Generated by Django 5.2 on 2026-08-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invitee_display_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
